spring:
  profiles:
    active: local


server:
  port: 7070


---
#local

spring.profiles: local

camel:
  spring:
    core-resource-name: core.xml
  path:
    home: /work/project/camel-launcher/src/main/resources
    conf: ${camel.path.home}/conf
  springboot:
    xml-routes-reload-directory: ${camel.path.conf}/router/
    xml-routes: file://${camel.path.conf}/router/*.xml
    main-run-controller: true


---
# test

spring.profiles: test

camel:
  spring:
    core-resource-name: core.xml
  path:
    home: /work/project/camel-launcher/src/test/resources
    conf: ${camel.path.home}/conf
  springboot:
    xml-routes-reload-directory: ${camel.path.conf}/router/
    xml-routes: file://${camel.path.conf}/router/process.xml
    main-run-controller: true