spring:
  profiles:
    active: local


server:
  port: 7070
  

 
---
##############################
### local
##############################
spring.profiles: local

# camel directory
camel:
    home: ${user.dir}/src/main/resources
    config: ${camel.home}/config
    route: ${camel.home}/route

# monitoring
management:
    security:
        enabled: false
    endpoints:
        web:
            exposure:
                include: "*"
    context-path: "/monitoring"
    port: "9090"
                

# camel route
camel:
    springboot:
        xml-routes-reload-directory: ${camel.route}
        xml-routes: file:${camel.route}/*.xml
        main-run-controller: true

logging:
    config: ${camel.config}/logback-spring.xml
---
# test

spring.profiles: test

# camel directory
camel:
    home: ${user.dir}/src/test/resources
    config: ${camel.home}/config
    route: ${camel.home}/route

# camel route
camel:
    springboot:
        xml-routes-reload-directory: ${camel.route}
        xml-routes: file:${camel.route}/*.xml
        main-run-controller: true
