spring:
  profiles:
    active: local


server:
  port: 7070
  


---
#local

spring.profiles: local

camel:
  spring:
    core-resource-name: core.xml
  path:
    home: ${user.dir}/src/main/resources
    conf: ${camel.path.home}/conf
  springboot:
    xml-routes-reload-directory: ${camel.path.conf}/route/
    xml-routes: file:/${camel.path.conf}/route/*.xml
    main-run-controller: true

logging:
    config: ${camel.path.conf}/logback-spring.xml
---
# test

spring.profiles: test


camel:
  spring:
    core-resource-name: core.xml
  path:
    home: /${user.dir}/src/test/resources
    conf: ${camel.path.home}/conf
  springboot:
    xml-routes-reload-directory: ${camel.path.conf}/route/
    xml-routes: ${camel.path.conf}/route/process.xml
    main-run-controller: true

logging:
    config: ${camel.path.conf}/logback-spring.xml
   
